### ISSUE TITLE
Duplication of subreadings in apertium-tagger

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium#156] opened 2022-03-07 19:02 UTC
Sometimes, when there are competing possibilities with subreadings, the tagger concatenates them. Example:

```
$ echo "jo qui’n diserèi" | apertium -d . oci_gascon-fra-disam
"<jo>"
	"jo" prn tn p1 mf sg
"<qui’n>"
	"qui" rel mf sp
		"en" prn pro adv
	"qui" prn itg mf sp
		"en" prn pro adv
"<diserèi>"
	"díser" vblex fti p1 sg
"<.>"
	"." sent

$ echo "^jo/jo<prn><tn><p1><mf><sg>$ ^qui’n/qui<rel><mf><sp>+en<prn><pro><adv>/qui<prn><itg><mf><sp>+en<prn><pro><adv>$ ^diserèi/díser<vblex><fti><p1><sg>$^./.<sent>$" | apertium-tagger -g $2 '/home/hector/apertium/apertium-oci-fra/oci-fra.prob'
^jo<prn><tn><p1><mf><sg>$ ^qui<rel><mf><sp>+en<prn><pro><adv>+en<prn><pro><adv>$ ^díser<vblex><fti><p1><sg>$^.<sent>$
```

(Notice `qui+en+en`)

Without the two finals words, it is working well:

```
$ echo "qui’n diserèi" | apertium -d . oci_gascon-fra-tagger
^qui<prn><itg><mf><sp>+en<prn><pro><adv>$ ^díser<vblex><fti><p1><sg>$^.<sent>$
```

**Comment by unhammer** [comment] 2022-03-08 08:29
Pretty sure this is a duplicate of https://github.com/apertium/apertium/issues/37 

My workaround is to have a set of rules at the bottom of the CG disambiguator that just picks one when it's ambiguous. 

https://github.com/apertium/apertium-nob/blob/233ee44a2979765bf1b4d33c3598842b7dbe0d7f/apertium-nob.nob.rlx#L36006-L36048

```

# Workarounds for https://github.com/apertium/apertium/issues/37 – try
# to remove ambiguity as much as possible when there are subreadings,
# doesn't matter so much what we pick at this point:
SELECT:issue37 SUB:1 n ;
SELECT:issue37 SUB:1 sg ;
SELECT:issue37 SUB:1 m ;
SELECT:issue37 SUB:1 f ;
SELECT:issue37 SUB:1 nt ;
SELECT:issue37 SUB:1 org ;
SELECT:issue37 SUB:1 al ;
SELECT:issue37 SUB:1 top ;
SELECT:issue37 SUB:1 np ;

SELECT:issue37 n IF (0/1 cmp) ;
SELECT:issue37 sg IF (0/1 cmp) ;
SELECT:issue37 m IF (0/1 cmp) ;
SELECT:issue37 f IF (0/1 cmp) ;
SELECT:issue37 nt IF (0/1 cmp) ;
SELECT:issue37 org IF (0/1 cmp) ;
SELECT:issue37 al IF (0/1 cmp) ;
SELECT:issue37 top IF (0/1 cmp) ;
SELECT:issue37 np IF (0/1 cmp) ;

SELECT:issue37 SUB:1 n ;
SELECT:issue37 SUB:1 sg ;
SELECT:issue37 SUB:1 m ;
SELECT:issue37 SUB:1 f ;
SELECT:issue37 SUB:1 nt ;
SELECT:issue37 SUB:1 org ;
SELECT:issue37 SUB:1 al ;
SELECT:issue37 SUB:1 top ;
SELECT:issue37 SUB:1 np ;

SELECT:issue37 SUB:2 n ;
SELECT:issue37 SUB:2 sg ;
SELECT:issue37 SUB:2 m ;
SELECT:issue37 SUB:2 f ;
SELECT:issue37 SUB:2 nt ;
SELECT:issue37 SUB:2 org ;
SELECT:issue37 SUB:2 al ;
SELECT:issue37 SUB:2 top ;
SELECT:issue37 SUB:2 np ;
```

**Comment by unhammer** [comment] 2022-03-08 08:30
(I'll close since we have #37, but feel free to reopen if you think there's a difference in the issues.)

**Closed by unhammer** 2022-03-08 08:30 UTC
