### ISSUE TITLE
mac os x compile problem

### ISSUE THREAD

**Issue by flammie** [apertium/apertium#81] opened 2020-06-24 21:48 UTC
I was trying to compile apertium on relatively fresh / vanilla mac and run into this problem:

```
...
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I/usr/local/include/lttoolbox-3.5 -I/opt/local/include/libxml2 -I/opt/local/include -I/usr/local/include/lttoolbox-3.5 -I/opt/local/include/libxml2 -I/opt/local/include -Wall -Wextra -g -O2 -std=c++2a -MT collection.lo -MD -MP -MF .deps/collection.Tpo -c collection.cc  -fno-common -DPIC -o .libs/collection.o
In file included from collection.cc:20:
In file included from ../apertium/serialiser.h:28:
/usr/local/include/lttoolbox-3.5/lttoolbox/serialiser.h:239:34: error: member
      reference base type 'const unsigned long' is not a structure or union
  uint64_t size = SerialisedType_.size();
                  ~~~~~~~~~~~~~~~^~~~~
collection.cc:98:23: note: in instantiation of member function '(anonymous
      namespace)::Serialiser<unsigned long>::serialise' requested here
  Serialiser<size_t>::serialise(element.size(), serialised);
                      ^
In file included from collection.cc:20:
In file included from ../apertium/serialiser.h:28:
/usr/local/include/lttoolbox-3.5/lttoolbox/serialiser.h:242:17: error: type
      'unsigned long' cannot be used prior to '::' because it has no members
  for (typename Container::const_iterator value_type_ =
                ^
In file included from collection.cc:21:
In file included from ../apertium/deserialiser.h:28:
/usr/local/include/lttoolbox-3.5/lttoolbox/deserialiser.h:194:66: error: member
      reference base type 'typename std::remove_const<unsigned long>::type'
      (aka 'unsigned long') is not a structure or union
  auto insert_it = std::inserter(SerialisedType_, SerialisedType_.begin());
                                                  ~~~~~~~~~~~~~~~^~~~~~
collection.cc:107:39: note: in instantiation of member function
      'Deserialiser<unsigned long>::deserialise' requested here
  size_t size = Deserialiser<size_t>::deserialise(serialised);
                                      ^
3 errors generated.
make[2]: *** [collection.lo] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
tpi006@uit-mac-219 apertium % 

```

I'm sure I've seen it on irc before but cannot find the solution atm.

**Comment by khannatanmai** [comment] 2020-06-25 02:44
I don't remember seeing this exact error (I tried to reproduce it but didn't get it), but what I remember is that when I installed apertium and lttoolbox, I used to get errors and I ran these commands (or can add them to the ~/.bash_profile), and it used to work:
```
export "CXXFLAGS=-O2 -I/opt/local/include"
CPATH=/opt/local/include
(for lttoolbox)

export "CXXFLAGS=-Wall -Wextra -O2 -DSIZET_NOT_CSTDINT=1"
(for apertium)


run ./configure after each
```

The catch is that recently we found out this CPATH line actually makes it not work for me so commenting it out works (this seems to be a version thing so I'm not sure which combination of this works), plus I tried commenting these out and running the build again and it works fine. But well, this is what I've done on Mac in the past to run the builds. Hope it helps :))

**Comment by TinoDidriksen** [comment] 2020-06-25 05:22
I thought I had fixed this. The important define is `SIZET_NOT_CSTDINT=1`, so `export "CXXFLAGS=-Wall -Wextra -O2 -DSIZET_NOT_CSTDINT=1"`

**Comment by khannatanmai** [comment] 2020-06-25 05:22
Was able to reproduce the error after commenting these out. 
```bash
In file included from ../apertium/serialiser.h:28:
/Users/khannatanmai/Documents/GSoC/repo/main/include/lttoolbox-3.5/lttoolbox/serialiser.h:239:34: error: 
      member reference base type 'const unsigned long' is not a structure or
      union
  uint64_t size = SerialisedType_.size();
                  ~~~~~~~~~~~~~~~^~~~~
collection.cc:98:23: note: in instantiation of member function '(anonymous
      namespace)::Serialiser<unsigned long>::serialise' requested here
  Serialiser<size_t>::serialise(element.size(), serialised);
                      ^
In file included from collection.cc:20:
In file included from ../apertium/serialiser.h:28:
/Users/khannatanmai/Documents/GSoC/repo/main/include/lttoolbox-3.5/lttoolbox/serialiser.h:242:17: error: 
      type 'unsigned long' cannot be used prior to '::' because it has no
      members
  for (typename Container::const_iterator value_type_ =
                ^
In file included from collection.cc:21:
In file included from ../apertium/deserialiser.h:28:
/Users/khannatanmai/Documents/GSoC/repo/main/include/lttoolbox-3.5/lttoolbox/deserialiser.h:194:66: error: 
      member reference base type 'typename std::remove_const<unsigned
      long>::type' (aka 'unsigned long') is not a structure or union
  auto insert_it = std::inserter(SerialisedType_, SerialisedType_.begin());
                                                  ~~~~~~~~~~~~~~~^~~~~~
collection.cc:107:39: note: in instantiation of member function
      'Deserialiser<unsigned long>::deserialise' requested here
  size_t size = Deserialiser<size_t>::deserialise(serialised);
                                      ^
3 errors generated.
make[2]: *** [collection.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by TinoDidriksen** [comment] 2020-06-25 05:24
I did fix this before. https://github.com/apertium/apertium/issues/57 closed by https://github.com/apertium/apertium/commit/537573c182324e0c00715725cf789bfbf4ceb4fa

**Comment by flammie** [comment] 2020-06-25 08:56
hmm, config.log has:
```
#define SIZET_NOT_CSTDINT 1
```
aha, it was just matter of missing include apertium_config.h in that file (since there is a config.h autostuff don't include -D switches on command line).  I'll fix...

**Closed** 2020-06-25 10:32 UTC
